import { useParams, useNavigate } from "react-router-dom";
import { mockBills } from "@/data/mockBills";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { ArrowLeft, ExternalLink, Calendar, User, MapPin, FileText, AlertCircle } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";

const statusColors = {
  'Introduced': 'bg-blue-100 text-blue-800 border-blue-200',
  'In Committee': 'bg-yellow-100 text-yellow-800 border-yellow-200',
  'Passed House': 'bg-purple-100 text-purple-800 border-purple-200',
  'Passed Senate': 'bg-indigo-100 text-indigo-800 border-indigo-200',
  'Enacted': 'bg-green-100 text-green-800 border-green-200',
  'Failed': 'bg-red-100 text-red-800 border-red-200'
};

const BillDetail = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const bill = mockBills.find(b => b.id === id);

  if (!bill) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <h2 className="text-2xl font-bold mb-4">Bill not found</h2>
          <Button onClick={() => navigate('/')}>Return to Dashboard</Button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white border-b border-gray-200">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <Button 
            variant="ghost" 
            onClick={() => navigate('/')}
            className="mb-4"
          >
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Dashboard
          </Button>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Bill Header */}
        <div className="bg-white rounded-lg shadow-lg p-8 mb-6">
          <div className="flex items-start justify-between mb-4">
            <div className="flex-1">
              <div className="flex items-center gap-3 mb-2">
                <FileText className="h-6 w-6 text-blue-600" />
                <span className="text-lg font-semibold text-gray-700">{bill.billNumber}</span>
              </div>
              <h1 className="text-3xl font-bold text-gray-900 mb-4">{bill.title}</h1>
            </div>
            <Badge className={`${statusColors[bill.status]} text-sm px-4 py-2`}>
              {bill.status}
            </Badge>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
            <div className="flex items-center gap-2 text-gray-600">
              <MapPin className="h-4 w-4" />
              <span><strong>State:</strong> {bill.state}</span>
            </div>
            <div className="flex items-center gap-2 text-gray-600">
              <User className="h-4 w-4" />
              <span><strong>Sponsor:</strong> {bill.sponsor}</span>
            </div>
            <div className="flex items-center gap-2 text-gray-600">
              <Calendar className="h-4 w-4" />
              <span><strong>Introduced:</strong> {new Date(bill.dateIntroduced).toLocaleDateString()}</span>
            </div>
          </div>

          <Separator className="my-6" />

          <div className="flex items-center justify-between">
            <div className="text-sm text-gray-600">
              <strong>Last Updated:</strong> {new Date(bill.lastUpdated).toLocaleDateString()}
            </div>
            <Button asChild>
              <a href={bill.originalLink} target="_blank" rel="noopener noreferrer">
                View Original Bill Text
                <ExternalLink className="h-4 w-4 ml-2" />
              </a>
            </Button>
          </div>
        </div>

        {/* AI Disclaimer */}
        <Alert className="mb-6">
          <AlertCircle className="h-4 w-4" />
          <AlertDescription>
            The summary and analysis below were generated by AI. Always refer to the original bill text for legal accuracy.
          </AlertDescription>
        </Alert>

        {/* AI-Generated Summary */}
        <Card className="mb-6">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <span className="text-blue-600">🤖</span>
              AI-Generated Summary
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-gray-700 leading-relaxed">{bill.summary}</p>
          </CardContent>
        </Card>

        {/* Scope */}
        <Card className="mb-6">
          <CardHeader>
            <CardTitle>Who Does This Apply To?</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-gray-700">{bill.scope}</p>
          </CardContent>
        </Card>

        {/* Models Covered */}
        <Card className="mb-6">
          <CardHeader>
            <CardTitle>AI Models Covered</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-gray-700">{bill.modelsCovered}</p>
          </CardContent>
        </Card>

        {/* Key Requirements */}
        <Card className="mb-6">
          <CardHeader>
            <CardTitle>Key Compliance Requirements</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3">
              {bill.keyRequirements.map((requirement, index) => (
                <li key={index} className="flex items-start gap-3">
                  <span className="flex-shrink-0 w-6 h-6 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-sm font-semibold">
                    {index + 1}
                  </span>
                  <span className="text-gray-700 pt-0.5">{requirement}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      </main>
    </div>
  );
};

export default BillDetail;